Make update not accidentally reset main repo

diff --git a/update b/update
--- a/update
+++ b/update
@@ -6,7 +6,10 @@ max_parallel_tasks=10
 
 git submodule | awk '{ print $2 }' \
   | xargs -I{} -P$max_parallel_tasks sh -c \
-  "echo 'Checking {}' \
-  && cd '{}' && git fetch --quiet \
-  && git reset --quiet --hard origin/HEAD \
-  || echo '** FAILED ** {}'"
+  "echo 'Checking {}'
+  if cd '{}'
+    then if [ -f .git ] #might be empty dir instead of proper submodule
+      then git fetch --quiet && git reset --quiet --hard origin/HEAD \
+        || echo ' ** Failed ** {}'
+    fi
+  fi"
